# Generated by Django 3.0.6 on 2020-05-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='username',
            new_name='notified_user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='was_viewed',
            new_name='viewed',
        ),
    ]
